// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsInventory.API.DbContexts;

namespace ProductsInventory.API.Migrations
{
    [DbContext(typeof(ProductsInventoryContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductsInventory.API.Entities.Products", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("productCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("releaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("starRating")
                        .HasColumnType("decimal(18,1)");

                    b.HasKey("productId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            description = "Leaf rake with 48-inch wooden handle.",
                            imageUrl = "assets/images/leaf_rake.png",
                            price = 19.95m,
                            productCode = "GDN-0011",
                            productName = "Leaf Rake",
                            releaseDate = "March 19, 2019",
                            starRating = 3.2m
                        },
                        new
                        {
                            productId = 2,
                            description = "5 gallon capacity rolling garden cart",
                            imageUrl = "assets/images/garden_cart.png",
                            price = 32.99m,
                            productCode = "GDN-0023",
                            productName = "Garden Cart",
                            releaseDate = "March 28, 2019",
                            starRating = 4.2m
                        },
                        new
                        {
                            productId = 3,
                            description = "Curved claw steel hammer",
                            imageUrl = "assets/images/hammer.png",
                            price = 8.99m,
                            productCode = "TBX-0048",
                            productName = "Hammer",
                            releaseDate = "May 21, 2019",
                            starRating = 4.8m
                        },
                        new
                        {
                            productId = 4,
                            description = "5-inch steel blade hand saw",
                            imageUrl = "assets/images/saw.png",
                            price = 11.55m,
                            productCode = "TBX-0022",
                            productName = "Saw",
                            releaseDate = "May 15, 2019",
                            starRating = 3.7m
                        },
                        new
                        {
                            productId = 5,
                            description = "tandard two-button video game controller",
                            imageUrl = "assets/images/xbox-controller.png",
                            price = 35.95m,
                            productCode = "GMG-0042",
                            productName = "Video Game Controller",
                            releaseDate = "October 15, 2018",
                            starRating = 4.6m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
